### ISSUE TITLE
How to reduce size of output to not be whole page?

### ISSUE THREAD

**Issue by steveschow** [dot-asterisk-nl/obsidian-lilypond#1]
Is there a way to set this up so that the output SVG will just the staves with music and not an entire empty page?

**Comment by Vaults** [comment]
Hi @steveschow, most people generally use `\include "lilypond-book-preamble.ly"` at the top of their script in Lilypond to achieve cropping.

**Comment by steveschow** [comment]
That does it.  Thanks.

**Comment by Chlorie** [comment]
> Hi [@steveschow](https://github.com/steveschow), most people generally use `\include "lilypond-book-preamble.ly"` at the top of their script in Lilypond to achieve cropping.

It seems that this is only useful for one-liners. If the score is, for example, two lines, lilypond will output two files for the lines and the plugin will fail to find the output. Is there a solution for this case?
